# Generated by Django 4.0.5 on 2022-07-03 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
    ]
