# Generated by Django 4.0.5 on 2022-07-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0003_solution_sub_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='lang',
            field=models.CharField(default='C++', max_length=50),
        ),
    ]
